[package]
name = "zkml"
version = "0.1.0"
edition = "2021"

[dependencies]
expander_compiler = { git = "https://github.com/PolyhedraZK/ExpanderCompilerCollection.git" }
tract-core = "0.21.10"
tract-onnx = "0.21.10"
